# Generated by Django 5.2.12 on 2026-09-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_track_release_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='free like a hummingbird', max_length=255)),
                ('body', models.TextField(blank=True, default='', help_text='Optional bio text shown under the heading. Blank lines start a new paragraph.')),
                ('booking_email', models.EmailField(blank=True, default='beingsaintted@gmail.com', max_length=254)),
                ('portrait', models.ImageField(blank=True, help_text="Optional. When empty, the site's default portrait is used.", null=True, upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About content',
            },
        ),
        migrations.CreateModel(
            name='LiveShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(help_text='Date and time the show starts')),
                ('venue', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, help_text='e.g. Lagos, Nigeria', max_length=255)),
                ('ticket_url', models.URLField(blank=True, help_text='Optional tickets / RSVP link')),
                ('note', models.CharField(blank=True, help_text="Optional short note, e.g. 'doors 7pm'", max_length=255)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
    ]
